CONTAINER POVLight
{
	NAME POVLight;
	INCLUDE Texpression;
	
	GROUP ID_TAGPROPERTIES
	{
	  REAL POV_LIGHT_TIGHTNESS           { UNIT REAL; MIN 0.0; MAX 1000.0; MAXSLIDER 100.0; STEP 0.1; ANIM OFF; CUSTOMGUI REALSLIDER;}
		REAL POV_LIGHT_FADE_DISTANCE       { UNIT REAL; MIN 0.0; MAX 1000.0; MAXSLIDER 100.0; STEP 0.1; ANIM OFF; CUSTOMGUI REALSLIDER;}
		REAL POV_LIGHT_FADE_POWER          { UNIT REAL; MIN 0.0; MAX 1000.0; MAXSLIDER 100.0; STEP 0.1; ANIM OFF; CUSTOMGUI REALSLIDER;}
		LONG POV_LIGHT_AREA_NUM_X { MIN 1; MAX 1000; MAXSLIDER 100; ANIM OFF; CUSTOMGUI LONGSLIDER;}
		LONG POV_LIGHT_AREA_NUM_Y { MIN 1; MAX 1000; MAXSLIDER 100; ANIM OFF; CUSTOMGUI LONGSLIDER;}

		STRING POV_LIGHT_PROJECTED_THROUGH {ANIM OFF;}

		REAL POV_LIGHT_ICON_TRANSPARENCY  { UNIT REAL; MIN 0.0; MAX 2; MAXSLIDER 1.1; STEP 0.01; ANIM OFF; CUSTOMGUI REALSLIDER;}

    BOOL POV_LIGHT_DISPLAY_ICON      {ANIM OFF;}
		BOOL POV_LIGHT_PARALLEL          {ANIM OFF;}
		BOOL POV_LIGHT_MEDIA_ATTENUATION {ANIM OFF;}
		BOOL POV_LIGHT_MEDIA_INTERACTION {ANIM OFF;}
	}
}
