#ifndef POV_LIGHT_H__
#define POV_LIGHT_H__

enum
{
	POV_LIGHT_PARALLEL          = 2101,
	POV_LIGHT_MEDIA_ATTENUATION = 2102,
	POV_LIGHT_MEDIA_INTERACTION = 2103,
	POV_LIGHT_DISPLAY_ICON      = 2104,

	POV_LIGHT_FADE_DISTANCE     = 2105,
  POV_LIGHT_FADE_POWER        = 2106,
  POV_LIGHT_PROJECTED_THROUGH = 2107,
	POV_LIGHT_AREA_NUM_X        = 2108,
	POV_LIGHT_AREA_NUM_Y        = 2109,
	POV_LIGHT_ICON_TRANSPARENCY = 2110,
	POV_LIGHT_TIGHTNESS         = 2111,
	POV_LIGHT_ICON_SCALE        = 2112,

	//////////////////////////////////////////////////////////////////////////

	_POV_LIGHT_END_
};

#endif // POV_LIGHT_H__
